### ISSUE TITLE
won't record between sessions

### ISSUE THREAD

**Issue by michaelpalumbo** [VCVRack/VCV-Recorder#26] opened 2019-11-01 14:03 UTC
vcv-recorder module where it won't let you record when operating in loaded sessions (i.e. adding a recorder module, when pressing record it works fine, but upon reopening rack (after closing for whatever the reason), the record button no longer responds (stays grey when clicking).

**Comment by AndrewBelt** [comment] 2019-11-01 15:45
Does setting the output file path in the module context menu allow Recorder to be used again?
Is there information about VCV Recorder printed to `log.txt`?

**Comment by AndrewBelt** [comment] 2020-08-24 13:47
Cannot reproduce issue and no user response, closing.

**Closed as completed by AndrewBelt** 2020-08-24 13:47 UTC
